### ISSUE TITLE
error installing rosie on mac

### ISSUE THREAD

**Issue by congmingwudi** [jamiejennings/homebrew-rosie#1]
Hi, I get this error when installing on my Mac, OS X El Capitan, 10.11.5. 

Ryans-MacBook-Pro:~ ryanc$ brew install rosie
Updating Homebrew...
==> Installing rosie from jamiejennings/rosie
==> Cloning https://github.com/jamiejennings/rosie-pattern-language.git
Updating /Users/ryanc/Library/Caches/Homebrew/rosie--git
==> Checking out branch master
==> make BREW=true
Last 15 lines from /Users/ryanc/Library/Logs/Homebrew/rosie/01.make:
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lstrlib.o lstrlib.c
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o ltablib.o ltablib.c
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lutf8lib.o lutf8lib.c
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o loadlib.o loadlib.c
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o linit.o linit.c
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o lutf8lib.o loadlib.o linit.o 
ranlib liblua.a
cc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_MACOSX    -c -o lua.o lua.c
cc -o lua   lua.o liblua.a -lm -lreadline 
ld: unexpected token: !tapi-tbd-v2 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libm.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [lua] Error 1
make[2]: *** [macosx] Error 2
make[1]: *** [macosx] Error 2
make: *** [bin/lua] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jamiejennings/homebrew-rosie/issues

**Comment by jamiejennings** [comment]
Thanks for the report!  It works on Sierra, so I will (1) make the formula enforce that, and (2) grab a machine running El Capitan and see if I can fix it.
If you are inclined to try cloning the repo (or downloading the tar file) and then running 'make', I would be interested to know if you get the same error.

**Comment by congmingwudi** [comment]
ah! My Sierra upgrade has been standing by for a week now, so it looks like it's time to run it.

**Comment by congmingwudi** [comment]
just to close this out... I upgraded to Sierra and initially got this error 

Ryans-MacBook-Pro:~ ryanc$ brew install rosie
Updating Homebrew...
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true
==> Installing rosie from jamiejennings/rosie
==> Installing dependencies for jamiejennings/rosie/rosie: readline
==> Installing jamiejennings/rosie/rosie dependency: readline
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing: git config --local --replace-all homebrew.private true

With help from this forum post -> http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

I ran this to install xcode, which cleared up the install failure. 

Ryans-MacBook-Pro:~ ryanc$ xcode-select --install
xcode-select: note: install requested for command line developer tools

Ryans-MacBook-Pro:~ ryanc$ brew install rosie
Updating Homebrew...
==> Installing rosie from jamiejennings/rosie
==> Cloning https://github.com/jamiejennings/rosie-pattern-language.git
Cloning into '/Users/ryanc/Library/Caches/Homebrew/rosie--git'...
remote: Counting objects: 136, done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 136 (delta 7), reused 55 (delta 4), pack-reused 0
Receiving objects: 100% (136/136), 5.91 MiB | 528.00 KiB/s, done.
Resolving deltas: 100% (7/7), done.
Checking connectivity... done.
==> Checking out branch master
==> make BREW=true
==> Rosie installed successfully!
==>     RPL libraries, documentation, etc are in /usr/local/share/rosie
==>     Executable will be linked (by brew) to /usr/local/bin/rosie
==>     Try this example, and look for color text output: rosie basic.matchall /
🍺  /usr/local/Cellar/rosie/current: 134 files, 12.1M, built in 41 seconds

the example command shown above doesn't work because this points to a directory, but this does:

Ryans-MacBook-Pro:~ ryanc$ rosie basic.matchall /usr/local/Cellar/rosie/current/INSTALL_RECEIPT.json
{ used_options : [ ] , unused_options : [ ] , built_as_bottle : false , poured_from_bottle : false , changed_files : null , time : 1480605408 , source_modified_time : 1480598462 , HEAD : 0f529dae1043639058130092cf35e68d18907cb8 , stdlib : null , compiler : clang , runtime_dependencies : [ ] , source : { path : /usr/local/Homebrew/Library/Taps/jamiejennings/homebrew-rosie/rosie.rb , tap : " jamiejennings /rosie " , spec : stable , versions : { stable : current , devel : null , head : null , version_scheme : 0 } } }

**Comment by jamiejennings** [comment]
Awesome!  I've updated the brew formula to explicitly require 'Xcode'.  I now expect brew to give a nice message about Xcode being missing and how to get it.

Thanks very much for the detailed feedback!
